# Generated by Django 5.2.5 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(
                max_length=1024, upload_to='will_not_be_used/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='state',
            field=models.SmallIntegerField(
                choices=[
                    (0, 'DRAFT'),
                    (1, 'PENDING REVIEW'),
                    (2, 'HIDDEN'),
                    (3, 'PUBLISHED'),
                ],
                db_index=True,
                default=0,
                verbose_name='문제 상태',
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.SmallIntegerField(
                choices=[
                    (0, 'RECEIVED'),
                    (1, 'COMPILING'),
                    (2, 'RUNNING'),
                    (3, 'JUDGING'),
                    (4, 'COMPILE_ERROR'),
                    (5, 'OK'),
                    (6, 'ACCEPTED'),
                    (7, 'WRONG_ANSWER'),
                    (8, 'RUNTIME_ERROR'),
                    (9, 'TIME_LIMIT_EXCEEDED'),
                    (10, "CANT_BE_JUDGED"),
                    (11, 'REJUDGE_REQUESTED'),
                ],
                db_index=True,
                default=0,
            ),
        ),
    ]
