# Generated by Django 5.2.5 on 2026-08-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_alter_attachment_file_alter_problem_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeJob',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('state', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('running', 'Running'),
                        ('complete', 'Complete'),
                        ('failed', 'Failed'),
                    ],
                    db_index=True,
                    default='pending',
                    max_length=16,
                )),
                ('worker_id', models.CharField(
                    blank=True, default='', max_length=128)),
                ('lease_expires_at', models.DateTimeField(
                    blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='judge_job',
                    to='judge.submission',
                )),
            ],
        ),
    ]
