# Generated by Django 5.2.5 on 2026-08-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_add_submit_date_index'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='content_type_set_for_%(class)s',
                to='contenttypes.contenttype',
                verbose_name='content type',
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_removed',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    'Check this box if the comment is inappropriate. A '
                    '"This comment has been removed" message will be '
                    'displayed instead.'
                ),
                verbose_name='is removed',
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_pk',
            field=models.CharField(
                db_index=True, max_length=64, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%(class)s_comments',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
