# Generated by Django 5.2.5 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='intro',
            field=models.TextField(default=''),
        ),
    ]
